ARG baseimage=debian:bullseye-slim
FROM ${baseimage} as builder-stage
ARG buildoptions
# workaround for memory bug https://github.com/rust-lang/cargo/issues/10583
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]
# ubuntu has different repo urls for amd64/arm64
RUN grep -qi ubuntu /etc/os-release && \
	if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then \
		sed -i '/^Signed-By:/a Architectures: amd64' \
			/etc/apt/sources.list.d/ubuntu.sources; \
	else \
		sed -i '/^deb /s/^deb /deb [arch=amd64] /' \
			/etc/apt/sources.list; \
	fi || true
RUN grep -qi ubuntu /etc/os-release && \
	if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then \
		sed -e 's|^URIs: .*|URIs: http://ports.ubuntu.com/ubuntu-ports/|' \
			-e '/^Architectures:/s/.*/Architectures: arm64/; t' \
			-e '/^Suites:/a Architectures: arm64' \
			/etc/apt/sources.list.d/ubuntu.sources \
			> /etc/apt/sources.list.d/ubuntu-arm64.sources; \
	else \
		sed -E '/^deb /s|deb.*http://[^ ]+|deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports|' \
			/etc/apt/sources.list \
			> /etc/apt/sources.list.d/ubuntu-arm64.list; \
	fi || true
RUN dpkg --add-architecture arm64
RUN apt update && apt-get install -y --no-install-recommends \
	build-essential crossbuild-essential-arm64 curl ca-certificates sudo git lintian \
	pkg-config libudev-dev:arm64 libssl-dev:arm64 libapt-pkg-dev:arm64 apt:amd64 \
	libclang-dev libpam0g-dev:arm64 pkgconf:arm64 zlib1g-dev:arm64 nettle-dev:arm64 \
	qemu-user-binfmt
RUN grep -qi bookworm /etc/os-release && apt-get install -y pkg-config:arm64 || true

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -sSf | sh -s -- -y
RUN source ~/.cargo/env && rustup target add aarch64-unknown-linux-gnu

COPY . /build/
WORKDIR /build

RUN df -h
RUN source ~/.cargo/env && ./build.sh ${buildoptions}

FROM scratch
COPY --from=builder-stage /build/*.log /build/packages/* /
