name: Release
run-name: Release ${{ github.ref_name }} ${{ github.event.inputs.version }} Debian/Trixie (arm64)

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        options:
        - 4.x
  push:
    tags:
      - 4.**

jobs:
  build:
    permissions:
      contents: write # needed for uploading new release
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Build packages
      run: |
        baseimage="debian:trixie-slim"
        echo "DEB_DIST=Debian/Trixie" >> $GITHUB_ENV
        echo "DEB_VERSION=1.4.7-1" >> $GITHUB_ENV
        echo "DEB_VERSION_UPSTREAM=1.4.7-1" >> $GITHUB_ENV
        cat $GITHUB_ENV >> .github/PREBUILD.md
        mkdir -p packages
        cp .github/PREBUILD.md packages/test.deb
    - name: Release packages
      run: |
        env
        gh release create ${DEB_VERSION} \
          --title "Version ${DEB_VERSION} (${DEB_DIST})" \
          --notes-file .github/PREBUILD.md \
          --draft \
          --latest=false \
          packages/*.deb
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
